import Header from "@/Components/Layout/Header";
import SideBar from "@/Components/UI/SideBar";
import TranscriptionList from "@/Components/UI/TranscriptionList/TranscriptionList";
import TranscriptionListHeader from "@/Components/UI/TranscriptionList/TranscriptionListHeader";
import { Geist, Geist_Mono } from "next/font/google";
import FilterUi from "./components/FilterUi";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <SideBar />
          <div className="w-full flex-col items-start">
            <Header />

            <div className="grid grid-cols-12">
              <div className="col-span-2 bg-white min-h-[calc(100vh-55px)]">
                <FilterUi />
              </div>
              <div className="col-span-3">
                <div className="m-4">
                  <TranscriptionListHeader />
                  <TranscriptionList />
                </div>
              </div>

              <div className="col-span-7">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
