import Header from "@/Components/Layout/Header";
import SideBar from "@/Components/UI/SideBar";
import TranscriptionList from "@/Components/UI/TranscriptionList/TranscriptionList";
import TranscriptionListHeader from "@/Components/UI/TranscriptionList/TranscriptionListHeader";
import { Geist, Geist_Mono } from "next/font/google";
import FilterUi from "./components/FilterUi";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <SideBar />
          <div className="w-full flex-col items-start">
            <Header />

            <div className="grid grid-cols-12">
              <div className="col-span-2 bg-white min-h-[calc(100vh-55px)]">
                <FilterUi />
              </div>
              <div className="col-span-3">
                <div className="m-4">
                  <TranscriptionListHeader />
                  <TranscriptionList
                    listData={[
                      {
                        companyLogo:
                          "https://images.pexels.com/photos/15406292/pexels-photo-15406292/free-photo-of-google-on-smartphone-touchscreen.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                        _id: 1,
                        name: "GOOGL",
                        recordDateTimeStamp: "Nov 23, 2024, 2:50 AM",
                        shortDescription:
                          "Alphabet Inc. Presents at BofA Securities Auto-motive",
                        venue: "Summit",
                        venueDateTimeStamp: "Apr-15-2025 08:50 AM",
                        participants: [
                          {
                            name: "Alan S. Lowe",
                            company: "Lumentum Holdings Inc.President",
                            designation: "CEO & Director",
                          },
                        ],
                        transcription: [
                          {
                            speaker: "Simon Matthew Leopold",
                            company: "Raymond James & Associates, Inc",
                            designation:
                              "Research Division, MD & Research Analyst",
                            content:
                              "Well, thanks a lot, folks, for joining us. My name is Simon Leopold from Raymond James. We're here at our Annual Tech Conference here in New York. And we've got a fireside chat session with Alan Lowe, the CEO of Lumentum. Alan, thanks for joining us.",
                          },
                          {
                            speaker: "Simon Matthew Leopold",
                            company: "Raymond James & Associates, Inc",
                            designation:
                              "Research Division, MD & Research Analyst",
                            content:
                              "Well, thanks a lot, folks, for joining us. My name is Simon Leopold from Raymond James. We're here at our Annual Tech Conference here in New York. And we've got a fireside chat session with Alan Lowe, the CEO of Lumentum. Alan, thanks for joining us.",
                          },
                        ],
                      },
                      {
                        companyLogo:
                          "https://images.pexels.com/photos/15406292/pexels-photo-15406292/free-photo-of-google-on-smartphone-touchscreen.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                        _id: 2,
                        name: "GOOGL",
                        recordDateTimeStamp: "Nov 23, 2024, 2:50 AM",
                        shortDescription:
                          "Alphabet Inc. Presents at BofA Securities Auto-motive",
                        venue: "Summit",
                        venueDateTimeStamp: "Apr-15-2025 08:50 AM",
                      },
                      {
                        companyLogo:
                          "https://images.pexels.com/photos/15406292/pexels-photo-15406292/free-photo-of-google-on-smartphone-touchscreen.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                        _id: 3,
                        name: "GOOGL",
                        recordDateTimeStamp: "Nov 23, 2024, 2:50 AM",
                        shortDescription:
                          "Alphabet Inc. Presents at BofA Securities Auto-motive",
                        venue: "Summit",
                        venueDateTimeStamp: "Apr-15-2025 08:50 AM",
                      },
                      {
                        companyLogo:
                          "https://images.pexels.com/photos/15406292/pexels-photo-15406292/free-photo-of-google-on-smartphone-touchscreen.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                        _id: 4,
                        name: "GOOGL",
                        recordDateTimeStamp: "Nov 23, 2024, 2:50 AM",
                        shortDescription:
                          "Alphabet Inc. Presents at BofA Securities Auto-motive",
                        venue: "Summit",
                        venueDateTimeStamp: "Apr-15-2025 08:50 AM",
                      },
                    ]}
                  />
                </div>
              </div>

              <div className="col-span-7">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
